AppEntrega3Trueba/urls.py
from django.urls import path
from AppEntrega3Trueba.views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('',inicio, name='Inicio'),
    path('jugadores/',jugadores, name='Jugadores'),
    path('estadios/',estadios,name='Estadios'),
    path('clubes/',clubes,name='Clubes'),
    #path('jugadoresFormulario/', jugadores_formulario, name="jugadoresFormulario"),
    #path('clubesFormulario/',clubes_formulario, name='clubesFormulario'),
    #path('estadiosFormulario/',estadios_formulario,name='estadiosFormulario'),
    path('buscarJugador/',buscar_jugador,name='buscarJugador'),
    path('buscandoJugador/',buscando_jugador),
    path('buscarClub/',buscar_club, name='buscarJugador'),
    path('buscandoClub/',buscando_club),
    path('buscarEstadio/',buscar_estadio,name='buscarEstadio'),
    path('buscandoEstadio/',buscando_estadio),

    path('leerJugadores/', leer_jugadores, name='leerJugadores'),
    path('eliminarJugador/<jugadorNombre>/',eliminar_jugadores, name="EliminarJugador"),
    path('editarJugadores/<jugadorNombre>/',editar_jugadores, name='EditarJugador'),


    path('club/list/', ListaClub.as_view(), name='LeerClubes'),
    path('club/<int:pk>/', DetalleClub.as_view(), name='DetalleClub'),
    path('club/crear/', CrearClub.as_view(),name='CrearClub'),
    path('club/editar/<int:pk>', ActualizarClub.as_view(),name='ActualizarClub'),
    path('club/borrar/<int:pk>', BorrarClub.as_view(),name='BorrarClub'),

    path('estadio/list/', ListaEstadio.as_view(), name='LeerEstadios'),
    path('estadio/<int:pk>/', DetalleEstadio.as_view(), name='DetalleEstadio'),
    path('estadio/crear/', CrearEstadio.as_view(),name='CrearEstadio'),
    path('estadio/editar/<int:pk>', ActualizarEstadio.as_view(),name='ActualizarEstadio'),
    path('estadio/borrar/<int:pk>', BorrarEstadio.as_view(),name='BorrarEstadio'),
    
    path('jugador/list/', ListaJugador.as_view(), name='LeerJugadores'),
    path('jugador/<int:pk>/', DetalleJugador.as_view(), name='DetalleJugador'),
    path('jugador/crear/', CrearJugador.as_view(),name='CrearJugador'),
    path('jugador/editar/<int:pk>', ActualizarJugador.as_view(),name='ActualizarJugador'),
    path('jugador/borrar/<int:pk>', BorrarJugador.as_view(),name='BorrarJugador'),


    path('login/', login_request, name ="Login"),
    path('registro/',registro, name='Register'),
    path('logout/',LogoutView.as_view(template_name ='AppEntrega3Trueba/logout.html'),name='Logout'),
    path('editar/', editar_usuario, name='EditarUsuario'),

    path('agregaravatar/',agregar_avatar,name='Avatar')

]

ProyectoEntrega3Trueba/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppEntrega3Trueba/',include('AppEntrega3Trueba.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppEntrega3Trueba/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Jugador(models.Model):

    nombre = models.CharField(max_length = 60)
    apellido = models.CharField(max_length = 60)
    alias = models.CharField(max_length = 60, null=True, blank=True) #NO ES OBLIGATORIO
    fecha_nacimiento = models.DateField()
    edad = models.IntegerField()
    nacionalidad = models.CharField(max_length = 60)
    posicion = models.CharField(max_length = 60, default=0)


    esta_retirado = models.BooleanField()
    goles = models.IntegerField()
    asistencias= models.IntegerField()
    cant_partidos = models.IntegerField()
    partidos_ganados = models.IntegerField(default=0)
    partidos_empatados = models.IntegerField(default=0)
    partidos_perdidos = models.IntegerField(default=0)

    #imagen = models.ImageField(upload_to="media", null=True)
    palmares = models.TextField(default=0)

    def __str__(self):
        return (f'{self.nombre} {self.apellido}')
    



class Estadio(models.Model):

    nombre = models.CharField(max_length = 60)
    nombre_fant = models.CharField(max_length = 60)
    capacidad = models.IntegerField()
    ubicacion = models.CharField(max_length = 60)
    club = models.CharField(max_length = 60)

    def __str__(self):
        return (f'Estadio {self.nombre_fant} (Estadio {self.nombre})')


class Club(models.Model):

    nombre = models.CharField(max_length = 60)
    apodos = models.CharField(max_length = 60)
    socios = models.IntegerField()
    division = models.CharField(max_length = 60)
    fundacion = models.DateField()
    colores_principales = models.CharField(max_length = 60)

    def __str__(self):
        return (f'{self.nombre}')
    

class Avatar(models.Model):

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares',null=True, blank=True)
    

AppEntrega3Trueba/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from AppEntrega3Trueba.models import Avatar


class JugadorFormulario(forms.Form):

    nombre = forms.CharField(max_length = 60)
    apellido = forms.CharField(max_length = 60)
    alias = forms.CharField(max_length = 60, required='False') #NO ES OBLIGATORIO
    fecha_nacimiento = forms.DateField()
    edad = forms.IntegerField()
    nacionalidad = forms.CharField(max_length = 60)
    posicion = forms.CharField(max_length = 60, )


    esta_retirado = forms.BooleanField()
    goles = forms.IntegerField()
    asistencias= forms.IntegerField()
    cant_partidos = forms.IntegerField()
    partidos_ganados = forms.IntegerField()
    partidos_empatados = forms.IntegerField()
    partidos_perdidos = forms.IntegerField()

    #imagen = forms.ImageField(upload_to="media", null=True)
    palmares = forms.CharField(max_length = 200)


class ClubFormulario(forms.Form):

    nombre = forms.CharField()
    apodos = forms.CharField()
    socios = forms.IntegerField()
    division = forms.CharField()
    fundacion = forms.DateField()
    colores_principales = forms.CharField()

    
class EstadioFormulario(forms.Form):
    nombre = forms.CharField()
    nombre_fant = forms.CharField()
    capacidad = forms.IntegerField()
    ubicacion = forms.CharField()
    club = forms.CharField()


class UsuarioRegistro(UserCreationForm):
    
    email = forms.EmailField()
    password1 = forms.CharField(label = 'Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label = 'Repetir la contraseña', widget=forms.PasswordInput)

    class Meta:

        model = User
        fields = ['username','email','first_name','last_name','password1','password2']
        help_texts = {k:'' for k in fields}


class FormularioEditar(UserCreationForm):

    email = forms.EmailField()
    password1 = forms.CharField(label = 'Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label = 'Repetir la contraseña', widget=forms.PasswordInput)

    class Meta:

        model = User
        fields = ['email','first_name','last_name','password1','password2']
        help_texts = {k:'' for k in fields}


class AvatarFormulario(forms.ModelForm):
    
    class Meta:
        model = Avatar
        fields=['imagen']

AppEntrega3Trueba/views.py
from django.shortcuts import render
from django.http import HttpResponse
from AppEntrega3Trueba.models import *
from AppEntrega3Trueba.forms import *
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


#from AppEntrega3Trueba.models import Curso

# Create your views here.


def login_request(request):

     if request.method == 'POST':

          form = AuthenticationForm(request, data = request.POST)

          if form.is_valid():

               usuario = form.cleaned_data.get('username')
               contraseña = form.cleaned_data.get('password')

               user = authenticate(username=usuario, password=contraseña)

               if user is not None:

                    login(request,user)

                    return render(request, 'AppEntrega3Trueba/inicio.html', {'mensaje':f'Bienvenido {user}'})
          else:

               return render(request, 'AppEntrega3Trueba/inicio.html', {'mensaje':'Datos incorrectos, intente de nuevo'})


     else:

          form = AuthenticationForm()
     
     return render(request, 'AppEntrega3Trueba/login.html', {'formulario':form})



def registro(request):

     if request.method == 'POST':

          form = UsuarioRegistro(request.POST)

          if form.is_valid():

               username = form.cleaned_data['username']
               form.save()
               return render(request, 'AppEntrega3Trueba/inicio.html', {'mensaje': 'Usuario creado.'})
     else:

          form = UsuarioRegistro()

     return render(request, 'AppEntrega3Trueba/registro.html',{'formulario':form})

@login_required
def editar_usuario(request):

     usuario = request.user

     if request.method == 'POST':

          form = FormularioEditar(request.POST)

          if form.is_valid():

               info = form.cleaned_data

               usuario.email = info['email']
               usuario.set_password(info['password1'])
               usuario.first_name = info['first_name']
               usuario.last_name = info['last_name']

               usuario.save()

               return render(request, 'AppEntrega3Trueba/inicio.html', {'mensaje':'Se ha editado correctamente tu usuario.'})

     else:

          form= FormularioEditar(initial= {
               'email':usuario.email,
               'first_name':usuario.first_name,
               'last_name':usuario.last_name,
          })
     
     return render(request,'AppEntrega3Trueba/editarPerfil.html', {'form':form, 'usuario':usuario})

def inicio(request):
    #return HttpResponse('Esta es la vista de bienvenida')
    return render(request,'AppEntrega3Trueba/inicio.html')


def jugadores(request): 
        if request.method == 'POST':
            
            mi_formulario = JugadorFormulario(request.POST)
            print(mi_formulario)

            if mi_formulario.is_valid:  
                 
                 
                informacion = mi_formulario.cleaned_data
      
                jugador = Jugador(nombre=informacion["nombre"], apellido=informacion["apellido"], alias=informacion["alias"], fecha_nacimiento=informacion["fecha_nacimiento"], edad=informacion["edad"], nacionalidad=informacion["nacionalidad"], posicion=informacion["posicion"], esta_retirado=informacion["esta_retirado"], goles=informacion["goles"], asistencias=informacion["asistencias"], cant_partidos=informacion["cant_partidos"], partidos_ganados=informacion["partidos_ganados"], partidos_empatados=informacion["partidos_empatados"], partidos_perdidos=informacion["partidos_perdidos"], palmares=informacion["palmares"] )
 
                jugador.save()
 
                return render(request, "AppEntrega3Trueba/inicio.html")
        
        else:

            mi_formulario = JugadorFormulario()
 
        return render(request,"AppEntrega3Trueba/jugadores.html", {'mi_formulario':mi_formulario})

def estadios(request):
    if request.method == 'POST':
            
            mi_formulario = EstadioFormulario(request.POST)
            print(mi_formulario)

            if mi_formulario.is_valid:
                 
                 
                informacion = mi_formulario.cleaned_data
      
                estadio = Estadio(nombre=informacion["nombre"], nombre_fant=informacion["nombre_fant"], capacidad=informacion["capacidad"], ubicacion=informacion["ubicacion"], club=informacion["club"], )

                estadio.save()
 
                return render(request, "AppEntrega3Trueba/inicio.html")
        
    else:
         mi_formulario = EstadioFormulario()
 
    return render(request,"AppEntrega3Trueba/estadios.html", {'mi_formulario':mi_formulario})

def clubes(request):
    if request.method == 'POST':
            
            mi_formulario = ClubFormulario(request.POST)
            print(mi_formulario)

            if mi_formulario.is_valid:
                 
                 
                informacion = mi_formulario.cleaned_data
      
                club = Club(nombre=informacion["nombre"], apodos=informacion["apodos"], socios=informacion["socios"], division=informacion["division"], fundacion=informacion["fundacion"], colores_principales=informacion["colores_principales"])

                club.save()
 
                return render(request, "AppEntrega3Trueba/inicio.html")
        
    else:
         mi_formulario = ClubFormulario()
 
    return render(request,"AppEntrega3Trueba/clubes.html", {'mi_formulario':mi_formulario})





def buscar_jugador(request):
     
     return render(request, 'AppEntrega3Trueba/buscarJugador.html')


def buscando_jugador(request):
     
     if request.GET['apellido']:
          apellido = request.GET['apellido']
          jugadores = Jugador.objects.filter(apellido__icontains=apellido)
     #respuesta = f'Buscando jugador con apellido {request.GET['apellido'] }'
          return render(request, 'AppEntrega3Trueba/resultadosBusquedaJugador.html', {'jugadores':jugadores, 'apellido':apellido})
     else:
          respuesta ="No se ha enviado ningún dato"

     return HttpResponse(respuesta)

def buscar_club(request):
     
     return render(request, 'AppEntrega3Trueba/buscarClub.html')

def buscando_club(request):
     if request.GET['nombre']:
          nombre = request.GET['nombre']
          clubes = Club.objects.filter(nombre__icontains=nombre)
          return render(request, 'AppEntrega3Trueba/resultadosBusquedaClub.html', {'clubes':clubes, 'nombre':nombre})
     else:
          respuesta ="No se ha enviado ningún dato"

     return HttpResponse(respuesta)


def buscar_estadio(request):
     
     return render(request, 'AppEntrega3Trueba/buscarEstadio.html')

def buscando_estadio(request):
     if request.GET['nombre_fant']:
          nombre_fant = request.GET['nombre_fant']
          estadios = Estadio.objects.filter(nombre_fant__icontains=nombre_fant)
          return render(request, 'AppEntrega3Trueba/resultadosBusquedaEstadio.html', {'estadios':estadios, 'nombre_fant':nombre_fant})
     else:
          respuesta ="No se ha enviado ningún dato"

     return HttpResponse(respuesta)



def leer_jugadores(request):

     jugador = Jugador.objects.all()

     contexto = {'jugadores': jugador}

     return render (request,'AppEntrega3Trueba/leerJugadores.html',contexto)

@login_required
def eliminar_jugadores(request, jugadorNombre):

     jugador = Jugador.objects.get(nombre=jugadorNombre)
     jugador.delete()

     jugadores = Jugador.objects.all()
     
     contexto = {'jugadores':jugadores}

     return render(request, "AppEntrega3Trueba/leerJugadores.html", contexto)


@login_required
def editar_jugadores(request, jugadorNombre):

     jugador = Jugador.objects.get(nombre=jugadorNombre)

     if request.method == 'POST':
          mi_formulario = JugadorFormulario(request.POST)
            

          if mi_formulario.is_valid():
                 
                 
               informacion = mi_formulario.cleaned_data
      

               jugador.nombre=informacion["nombre"]
               jugador.apellido=informacion["apellido"]
               jugador.alias=informacion["alias"]
               jugador.fecha_nacimiento=informacion["fecha_nacimiento"]
               jugador.edad=informacion["edad"]
               jugador.nacionalidad=informacion["nacionalidad"]
               jugador.posicion=informacion["posicion"]
               jugador.esta_retirado=informacion["esta_retirado"]
               jugador.goles=informacion["goles"]
               jugador.asistencias=informacion["asistencias"]
               jugador.cant_partidos=informacion["cant_partidos"]
               jugador.partidos_ganados=informacion["partidos_ganados"]
               jugador.partidos_empatados=informacion["partidos_empatados"]
               jugador.partidos_perdidos=informacion["partidos_perdidos"]
               jugador.palmares=informacion["palmares"]


               jugador.save()
 
               return render(request, "AppEntrega3Trueba/inicio.html")  
     else:
          mi_formulario = JugadorFormulario(initial={'nombre':jugador.nombre, 'apellido':jugador.apellido,
          'alias':jugador.alias,'fecha_nacimiento':jugador.fecha_nacimiento,'edad':jugador.edad,
          'nacionalidad':jugador.nacionalidad,'posicion':jugador.posicion,
          'esta_retirado':jugador.esta_retirado,'goles':jugador.goles,'asistencias':jugador.asistencias,
          'cant_partidos':jugador.cant_partidos,'partidos_ganados':jugador.partidos_ganados,
          'partidos_empatados':jugador.partidos_empatados,'partidos_perdidos':jugador.partidos_perdidos,
          'palmares':jugador.palmares})
 

AppEntrega3Trueba/templates/AppEntrega3Trueba/agregarAvatar.html
{% extends "AppEntrega3Trueba/padre.html" %}
{% load static %}
{% block title %}Agregar avatar{% endblock title %}Iniciar sesion

{% block título %}


Aca podemos agregar un avatar

{% endblock %}

{% block descripción %}

<form action="" method="POST" enctype='multipart/form-data'> {% csrf_token %}


    {{formulario.as_p}}

    <button type="submit">Enviar</button>


</form>

{% endblock %}

AppEntrega3Trueba/templates/AppEntrega3Trueba/buscarEstadio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Busqueda de estadio</title>
</head>
<body>
    <p>Agregue nombre fantasioso del estadio:</p>
    <form action="/AppEntrega3Trueba/buscandoEstadio" method="GET">

        <input type="text" name="nombre_fant" id="nombre_fant">

        <input type="submit" value="Enviar">

    </form>
</body>
</html>

AppEntrega3Trueba/templates/AppEntrega3Trueba/club_confirm_delete.html
{% extends "AppEntrega3Trueba/padre.html" %}
{% load static %}

{%block title %}Borrar club{% endblock %}

{% block título %}<h1>Borrar club</h1>{% endblock %}

{% block descripción %}
    <form action="" method="post">  {% csrf_token %}

        <p>Estas seguro que quieres eliminar este club?</p>

        <input type="submit" value="Confirmar">
    </form>
{% endblock %}

AppEntrega3Trueba/templates/AppEntrega3Trueba/club_detail.html
{% extends "AppEntrega3Trueba/padre.html" %}
{% load static %}

{%block title %}Club {{club.nombre}}{% endblock %}

{% block título %}

    <h1>Nombre: {{club.nombre}}  </h1>
{% endblock %}

{% block descripción %}
    <strong><h4><li>Nombre: {{jugador.nombre}}  </li>
        <li>Apellido: {{jugador.apellido}}  </li>
        <li>Alias: {{jugador.alias}}  </li>
        <li>Fecha de nacimiento: {{jugador.fecha_nacimiento}}  </li>
        <li>Edad: {{jugador.edad}} años </li>
        <li>Nacionalidad: {{jugador.nacionalidad}}  </li>
        <li>Posición: {{jugador.posicion}}  </li>
        <li>Está retirado? {{jugador.esta_retirado}}  </li>
        <li>Goles totales: {{jugador.goles}}  </li>
        <li>Asistencias totales: {{jugador.asistencias}}  </li>
        <li>Cantidad de partidos: {{jugador.cant_partidos}}  </li>
        <li>Partidos ganados: {{jugador.partidos_ganados}}  </li>
        <li>Partidos empatados: {{jugador.partidos_empatados}}  </li>
        <li>Partidos perdidos: {{jugador.partidos_perdidos}}  </li>
        <li>Palmarés: {{jugador.palmares}}  </li>

    <a href="{% url 'LeerJugadores' %}">Regresar</a></strong></h4>

{% endblock %}

AppEntrega3Trueba/templates/AppEntrega3Trueba/club_form.html
{% extends "AppEntrega3Trueba/padre.html" %}
{% load static %}

{%block title %}Crear club{% endblock %}

{% block título %}<h1>Crear club</h1> {% endblock %}

{% block descripción %}
    <form action="" method="post">  {% csrf_token %}

        {{form.as_p}}

        <input type="submit" value="Enviar">
    </form>

{% endblock %}

AppEntrega3Trueba/templates/AppEntrega3Trueba/club_list.html
{% extends "AppEntrega3Trueba/padre.html" %}
{% load static %}

{%block title %}Lista de clubes{% endblock %}

{% block título %}


<h1>Lista de clubes</h1>
{% endblock %}

{% block info %}
    
    {% for club in object_list %}
    <li>Nombre: {{club.nombre}}  </li>


<button><a href="{% url 'DetalleClub' club.id %}">Ver club</a></button>
<button><a href="{% url 'ActualizarClub' club.id %}">Actualizar club</a></button>
<button><a href="{% url 'BorrarClub' club.id %}">Eliminar club</a></button>



<p>--------------------</p>





{% endfor %}

<button><a href="{% url 'CrearClub' %}">Crear club</a></button>

{% endblock %}

AppEntrega3Trueba/templates/AppEntrega3Trueba/clubes.html
{% extends "AppEntrega3Trueba/padre.html" %}



{% load static %}




{% block título %}


Clubes

{% endblock %}

{% block descripción %}

<h1>Agregar clubes</h1>
    {% if mi_formulario.errors %}
    <div style="background-color: red;"><p>ERROR EN LOS DATOS</p></div>
    {% endif %}

    <form action=""    method="POST"> {% csrf_token %}
       <table>

        {{ mi_formulario.as_table }}
       </table>
                

        <input type = "submit" value="Enviar">
     </form>

{% endblock %}

AppEntrega3Trueba/templates/AppEntrega3Trueba/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}Futarg{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'AppEntrega3Trueba/css/styles.css' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppEntrega3Trueba/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Inicio' %}">Futarg</a>
                <a class="btn btn-primary" href="{% url 'Jugadores' %}">Jugadores</a>
                <a class="btn btn-primary" href="{% url 'Estadios' %}">Estadios</a>
                <a class="btn btn-primary" href="{% url 'Clubes' %}">Clubes</a>

                {% if request.user.is_authenticated %}


                <p>{{user.username}}</p>
                {% with user.avatar_set.first as miAvatar %}
                {% if miAvatar %}
                <img src='{{miAvatar.imagen.url}}' alt='No encontro imagen' style='max-width:50px'>
                {% endif %}
                {% endwith %}
                <a class="btn btn-primary" href="{% url 'EditarUsuario' %}">Editar perfil</a>
                <a class="btn btn-primary" href="{% url 'Logout' %}">Logout</a>

                {% else %}

                <a class="btn btn-primary" href="{% url 'Login' %}">Login</a>
                <a class="btn btn-primary" href="{% url 'Register' %}">Registro</a>
                {% endif %}


            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                
                                {% block título %}


                                {% endblock %}

                            </h1>
                            <!-- Signup form-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            
                            {% block descripción %}

                            {% endblock %}

                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Icons Grid-->
        <section style='height:1000px'>
            <div class="container">
                <div class="row">
                    {% block info %}


                    {% endblock %}
                </div>
            </div>
        </section>
        <!-- Image Showcases-->
        <section class="showcase">
            <div class="container-fluid p-0">
                <div class="row g-0">
                    
                <div class="row g-0">
                    <
                <div class="row g-0">
                   
            </div>
        </section>
        <!-- Testimonials-->
        
        <!-- Call to Action-->
        
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'AppEntrega3Trueba/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>